# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Osiris Hass Addon
version: "0.0.2"
slug: osiris
description: Communicate with osiris
url: "https://github.com/limberger/osiris_hass_addon/tree/main/osiris"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello from osiris..."
schema:
  message: "str?"
image: "limberger/{arch}-osiris_hass_addon"