# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "0.0.1"
slug: osiris
description: Example add-on
url: "https://github.com/limberger/osiris_hass_addon/tree/main/osiris"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "limberger/osiris_hass_addon/{arch}-osiris_hass_addon"